### ISSUE TITLE
Add VarBC coefficient time-series plotting tool

### ISSUE THREAD

**Issue by ewhelan** [Hirlam/AccordDaTools#4]
Hola @JanaSanchez 

As discussed, do you have something we could use here?

Eoin

**Comment by JanaSanchez** [comment]
What exactly are you looking for @ewhelan ?

**Comment by ewhelan** [comment]
I am looking for the plotting software/tool used by some to show the evolution of VarBC coefficients in time. I am in touch with Joan on another e-mail thread in this regard. He has promised a copy soon. I think you are off the hook (for now!).

Thanks for the reply! 

Eoin

**Comment by roelstappers** [comment]
In addition to time series, scatterplots of the parameter increments, split by assimilation time, are also very useful diagnostic tool. See e.g. [VarBC correlations.pdf](https://github.com/Hirlam/AccordDaTools/files/7538534/VarBC.correlations_roel.pdf). The subspace spanned by params 8 and 10 (linear and cubic view angle dependence) are linear dependent both at ECMWF and in Harmonie. So the estimates for param 8 and 10 never converge. At ECMWF we also see a clear split between the increments for 00 and 12 UTC for params 0,1,2,3,5.

**Comment by ewhelan** [comment]
Beautiful! Looking forward to a PR from you @roelstappers !

**Comment by magnuslindskog** [comment]
I think Joan has developed such a tool that he will present at next weeks meeting. I am trying to convince Reima to find time to add a tool for diagnosing funtiinality of cloud detection as well.

**Comment by ewhelan** [comment]
PR #9 has addressed this. Closing.
